export const sourceList = [
  // Password Manager List
  {
    id: "password-manager--1password",
    name: "1Password",
    logo: null,
    title: "Upload file from 1Password",
    prepareFileMessage: "Download CSV file from 1Password",
    group: "password-manager",
  },
  {
    id: "password-manager--dashlane",
    name: "Dashlane",
    logo: null,
    title: "Upload file from Dashlane",
    prepareFileMessage: "Download CSV file from Dashlane",
    group: "password-manager",
  },
  {
    id: "password-manager--lastpass",
    name: "LastPass",
    logo: null,
    title: "Upload file from LastPass",
    prepareFileMessage: "Download CSV file from LastPass",
    group: "password-manager",
  },
  {
    id: "password-manager--bitwarden",
    name: "Bitwarden",
    logo: null,
    title: "Upload file from Bitwarden",
    prepareFileMessage: "Download CSV file from Bitwarden",
    group: "password-manager",
  },
  {
    id: "password-manager--keeper",
    name: "Keeper",
    logo: null,
    title: "Upload file from Keeper",
    prepareFileMessage: "Download CSV file from Keeper",
    group: "password-manager",
  },
  {
    id: "password-manager--keychain",
    name: "Keychain",
    logo: null,
    title: "Upload file from Keychain",
    prepareFileMessage: "Download CSV file from Keychain",
    group: "password-manager",
  },
  {
    id: "password-manager--other",
    name: "Other",
    logo: null,
    title: "Upload file file",
    prepareFileMessage: "Prepare your CSV file",
    group: "password-manager",
  },

  // Browser List
  {
    id: "browser--chrome",
    name: "Chrome",
    logo: null,
    title: "Upload file from Chrome",
    prepareFileMessage: "Download CSV file from Chrome",
    group: "browser",
  },
  {
    id: "browser--brave",
    name: "Brave",
    logo: null,
    title: "Upload file from Brave",
    prepareFileMessage: "Download CSV file from Brave",
    group: "browser",
  },
  {
    id: "browser--safari",
    name: "Safari",
    logo: null,
    title: "Upload file from Safari",
    prepareFileMessage: "Download CSV file from Safari",
    group: "browser",
  },
  {
    id: "browser--firefox",
    name: "Firefox",
    logo: null,
    title: "Upload file from Firefox",
    prepareFileMessage: "Download CSV file from Firefox",
    group: "browser",
  },
  {
    id: "browser--microsoft-edge",
    name: "Microsoft Edge",
    logo: null,
    title: "Upload file from Microsoft Edge",
    prepareFileMessage: "Download CSV file from Microsoft Edge",
    group: "browser",
  },
  {
    id: "browser--opera",
    name: "Opera",
    logo: null,
    title: "Upload file from Opera",
    prepareFileMessage: "Download CSV file from Opera",
    group: "browser",
  },
  {
    id: "browser--other",
    name: "Other",
    logo: null,
    title: "Upload file file",
    prepareFileMessage: "Prepare your CSV file",
    group: "browser",
  },

  // My computer List
  {
    id: "`my-computer--upload-csv-file",
    name: "Upload CSV file",
    logo: null,
    title: "Upload file from your device",
    prepareFileMessage: "Prepare your CSV file",
    group: "my-computer",
  },
];
